name: Build mitmproxy with pycryptodome

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.x']

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Clone mitmproxy repository
      run: git clone https://github.com/mitmproxy/mitmproxy.git

    - name: Install dependencies (Linux)
      if: runner.os == 'Linux'
      run: |
        cd mitmproxy
        python -m venv venv
        source venv/bin/activate
        pip install pycryptodome
        deactivate
        venv/bin/pip install -e ".[dev]"
        mkdir -p ../lib/mitmproxy/linux
        cp -r ./venv/* ../lib/mitmproxy/linux

    - name: Install dependencies (Windows)
      if: runner.os == 'Windows'
      run: |
        cd mitmproxy
        python -m venv venv
        .\venv\Scripts\activate
        pip install pycryptodome
        .\venv\Scripts\deactivate
        .\venv\Scripts\pip install -e ".[dev]"
        New-Item -Path ..\lib\mitmproxy\windows -ItemType Directory -Force
        Copy-Item -Path .\venv\* -Destination ..\lib\mitmproxy\windows -Recurse

    - name: Install dependencies (macOS)
      if: runner.os == 'macOS'
      run: |
        cd mitmproxy
        python3 -m venv venv
        source venv/bin/activate
        pip install pycryptodome
        deactivate
        venv/bin/pip install -e ".[dev]"
        mkdir -p ../lib/mitmproxy/macos
        cp -r ./venv/* ../lib/mitmproxy/macos
